import '@testing-library/jest-dom/vitest';

const mockHarness = {
  reset: () => {},
  setOpenFileResult: () => {},
  setOpenImageFileResult: () => {},
  setSaveFileResult: () => {},
  readStoredFile: () => null,
  readStoredBinaryBase64: () => null,
  listStoredFiles: () => [],
  seedFile: () => {},
  seedBinaryFile: () => {},
  setImportDocResult: () => {},
  setSpellCheckResults: () => {},
  setSpellSuggestions: () => {},
  setSettings: () => {},
  setRecents: () => {},
  getRecents: () => [],
  setEditor: () => {},
  loadEditorContent: () => {},
  getEditorJson: () => null,
  getEditorText: () => '',
  getEditorSelectionText: () => '',
  runEditorCommand: () => {},
  isDirty: () => false,
  setPendingFile: () => {},
  emitOpenFile: () => {},
  emitSaveAndClose: () => {},
  getExportPdfCallCount: () => 0,
  getPrintCallCount: () => 0,
};

window.dansword = {
  openFile: async () => null,
  openImageFile: async () => null,
  saveFile: async (defaultPath?: string) => defaultPath ?? 'C:\\DansWordTest\\Untitled.docx',
  openFolder: async () => 'C:\\DansWordTest',
  readFile: async () => new Uint8Array(),
  readTextFile: async () => '',
  writeFile: async () => true,
  listDocuments: async () => [],
  getSettings: async () => null,
  setSettings: async () => true,
  getRecents: async () => [],
  setRecents: async () => true,
  getDefaultSaveDir: async () => 'C:\\DansWordTest',
  printDocument: async () => true,
  saveRevision: async () => ({
    id: 'rev-1',
    label: 'Saved',
    timestamp: Date.parse('2026-01-15T12:00:00.000Z'),
    filePath: 'C:\\DansWordTest\\Untitled.docx',
  }),
  listRevisions: async () => [],
  loadRevision: async () => ({}),
  exportPdf: async () => new Uint8Array(),
  importDoc: async () => ({
    format: 'text',
    data: 'Legacy doc text',
    source: 'extractor',
    warning: 'Test mock import',
  }),
  spellCheckWords: async (words: string[]) => words.map(() => true),
  spellSuggest: async () => ['suggestion'],
  setDirty: async () => true,
  closeNow: async () => true,
  onSaveAndClose: () => () => {},
  takePendingFile: async () => null,
  onOpenFile: () => () => {},
};

window.__DANSWORD_TEST__ = mockHarness;
